### ISSUE TITLE
Tracker: Secure ArgoCD integration in a multi-tenant/multi-cluster environment

### ISSUE THREAD

**Issue by NiklasRosenstein** [helsing-ai/nyl#16]
They way Nyl is currently integrated into ArgoCD as a [CMP](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/) is not secure in an environment where ArgoCD hosts multiple tenants and clusters.

Here we consider a "tenant" to be for example another team in the organization that should have exclusive access to its own resources or cluster, and the secrets injected into its Kubernetes manifests.

This issue is a tracker for the related sub-issues to enable a multi-tenant secure Nyl and ArgoCD integration.

### Issues

* [ ] https://github.com/NiklasRosenstein/nyl/issues/48
* [ ] https://github.com/NiklasRosenstein/nyl/issues/27
* [ ] https://github.com/NiklasRosenstein/nyl/issues/49
* [ ] #108
